# Generated by Django 4.0.4 on 2022-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
