# Generated by Django 4.0.4 on 2022-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_signup_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rememberuser',
            field=models.BooleanField(default=False),
        ),
    ]
