# Generated by Django 4.0.4 on 2022-08-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_rememberuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
