# Generated by Django 4.0.4 on 2022-08-10 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_ign'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingamename', models.CharField(blank=True, max_length=50, null=True)),
                ('gametype', models.CharField(blank=True, max_length=50, null=True)),
                ('gamerole', models.CharField(blank=True, max_length=50, null=True)),
                ('formerteam', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
