# Generated by Django 4.0.4 on 2022-08-14 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_avatar_customuser_formerteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='formerteam',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gamerole',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gametype',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ingamename',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('gametype', models.CharField(blank=True, max_length=50, null=True)),
                ('gamerole', models.CharField(blank=True, max_length=50, null=True)),
                ('formerteam', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
