# Generated by Django 4.0.4 on 2022-08-16 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='prodpect_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='prodpect_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
