# Generated by Django 4.0.4 on 2022-08-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_profilehighlights_feedback_reviewuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewuser',
            name='author',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, null=True),
        ),
    ]
