# Generated by Django 4.0.4 on 2022-08-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_reviewuser_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
