# Generated by Django 4.0.4 on 2022-08-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_reviewuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewuser',
            name='slug',
        ),
    ]
