# Generated by Django 4.0.4 on 2022-08-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_reviewuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewuser',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
