# Generated by Django 4.0.4 on 2022-08-30 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_reviewuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehighlights',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='view_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilehighlights',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='view_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
