# Generated by Django 4.0.4 on 2022-08-30 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_customuser_options_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a03bee8-f06c-4e19-9fda-fe659f4cc1f6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
